// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/dashboard/data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/dashboard/data.get').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/login.post').default>>>>
    }
    '/api/suppliers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/suppliers/[id].get').default>>>>
    }
    '/api/suppliers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/suppliers/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}